services:
  db:
    image: postgres:16
    container_name: etl-debug-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./etl-debug-db-init-scripts:/docker-entrypoint-initdb.d
      - ./unencrypted:/tmp/unencrypted
volumes:
  db_data: