#!/usr/bin/env zsh

read_env() {
    grep "$1" .env | awk -F= '{print $2}'
}
export PGPASSWORD="$(read_env 'DB_PASSWORD')"
DB_USER="$(read_env 'DB_USER')"
DB_NAME="$(read_env 'DB_NAME')"

run_psql_command() {
    COMMAND="$1"
    psql -U "$DB_USER" -d "$DB_NAME" -h localhost -c "$COMMAND"
}

# Insert LTC BED YTD OCCUPIED DAYS

# Create table
run_psql_command \
"CREATE TABLE IF NOT EXISTS ltc_bed_ytd_occupied_days (
    id SERIAL PRIMARY KEY,
    CONFIRMATION_ID VARCHAR(8),
    OCC_QUARTER VARCHAR(2),
    OCC_MONTH VARCHAR(12),
    OCC_DAYS_YTD_IN_SCOPE_PUBLIC REAL,
    OCC_DAYS_YTD_OUT_SCOPE_PUBLIC REAL,
    OCC_DAYS_YTD_PRIVATE REAL,
    OCC_DAYS_YTD_TOTAL_DAYS REAL);" >&2;

# Insert records
run_psql_command "DELETE FROM ltc_bed_ytd_occupied_days;"
for file in $(find -L unencrypted -name "*ltc_bed_ytd_occupied_days*.csv" -not -name "*_tot_*"); do
    run_psql_command \
    "COPY ltc_bed_ytd_occupied_days (
    CONFIRMATION_ID,
    OCC_QUARTER,
    OCC_MONTH,
    OCC_DAYS_YTD_IN_SCOPE_PUBLIC,
    OCC_DAYS_YTD_OUT_SCOPE_PUBLIC,
    OCC_DAYS_YTD_PRIVATE,OCC_DAYS_YTD_TOTAL_DAYS
    )
    FROM '/tmp/$file' WITH
    (FORMAT csv, HEADER true, QUOTE '\"', NULL '', FORCE_NULL (
    OCC_DAYS_YTD_IN_SCOPE_PUBLIC,
    OCC_DAYS_YTD_OUT_SCOPE_PUBLIC,
    OCC_DAYS_YTD_PRIVATE,OCC_DAYS_YTD_TOTAL_DAYS));" >&2
done

# Insert LTC BUDGET DIRECT CARE COST

# Create table
TABLE_2="ltc_budget_direct_care_cost"
run_psql_command \
"CREATE TABLE IF NOT EXISTS "$TABLE_2" (
    id SERIAL PRIMARY KEY,
    CONFIRMATION_ID VARCHAR(8),
    DIR_CARE_COST_TYPE VARCHAR(32),
    DIR_CARE_COST_NAME VARCHAR(32),
    DIR_CARE_OTHER_VALUE VARCHAR(64),
    DIR_CARE_COST_PROD_HRS_REG REAL,
    DIR_CARE_COST_PROD_HRS_OT REAL,
    DIR_CARE_COST_PROD_HRS_ORIENTATION REAL,
    DIR_CARE_CST_PROD_HRS_CONTRACTED REAL,
    DIR_CARE_COST_PROD_HRS_AGENCY_STUFF_UTIL REAL,
    DIR_CARE_COST_PROD_HRS_SUBTOTAL REAL,
    DIR_CARE_COST_PROD_HRS_TOTAL REAL,
    DIR_CARE_COST_NON_PROD_HRS_VAC REAL,
    DIR_CARE_COST_NON_PROD_HRS_SICK REAL,
    DIR_CARE_COST_NON_PROD_HRS_OTHER REAL,
    DIR_CARE_COST_NON_PROD_HRS_TOTAL REAL,
    DIR_CARE_COST_TOTAL_HRS_PAID REAL,
    DIR_CARE_COST_HOURLY_RATE_STAFF REAL,
    DIR_CARE_COST_HOURLY_RATE_CONTRACTED REAL);" >&2

run_psql_command "DELETE FROM "$TABLE_2""
for file in $(find -L unencrypted -name "*ltc_budget_direct_care_cost*.csv" -not -name "*_subs_*"); do
    run_psql_command \
    "COPY "$TABLE_2" 
    (CONFIRMATION_ID,
    DIR_CARE_COST_TYPE,
    DIR_CARE_COST_NAME,
    DIR_CARE_OTHER_VALUE,
    DIR_CARE_COST_PROD_HRS_REG,
    DIR_CARE_COST_PROD_HRS_OT,
    DIR_CARE_COST_PROD_HRS_ORIENTATION,
    DIR_CARE_CST_PROD_HRS_CONTRACTED,
    DIR_CARE_COST_PROD_HRS_AGENCY_STUFF_UTIL,
    DIR_CARE_COST_PROD_HRS_SUBTOTAL,
    DIR_CARE_COST_PROD_HRS_TOTAL,
    DIR_CARE_COST_NON_PROD_HRS_VAC,
    DIR_CARE_COST_NON_PROD_HRS_SICK,
    DIR_CARE_COST_NON_PROD_HRS_OTHER,
    DIR_CARE_COST_NON_PROD_HRS_TOTAL,
    DIR_CARE_COST_TOTAL_HRS_PAID,
    DIR_CARE_COST_HOURLY_RATE_STAFF,
    DIR_CARE_COST_HOURLY_RATE_CONTRACTED)
    FROM '/tmp/$file' WITH
    (FORMAT csv, HEADER true, QUOTE '\"', NULL '', FORCE_NULL (
    DIR_CARE_COST_PROD_HRS_REG,
    DIR_CARE_COST_PROD_HRS_OT,
    DIR_CARE_COST_PROD_HRS_ORIENTATION,
    DIR_CARE_CST_PROD_HRS_CONTRACTED,
    DIR_CARE_COST_PROD_HRS_AGENCY_STUFF_UTIL,
    DIR_CARE_COST_PROD_HRS_SUBTOTAL,
    DIR_CARE_COST_PROD_HRS_TOTAL,
    DIR_CARE_COST_NON_PROD_HRS_VAC,
    DIR_CARE_COST_NON_PROD_HRS_SICK,
    DIR_CARE_COST_NON_PROD_HRS_OTHER,
    DIR_CARE_COST_NON_PROD_HRS_TOTAL,
    DIR_CARE_COST_TOTAL_HRS_PAID,
    DIR_CARE_COST_HOURLY_RATE_STAFF,
    DIR_CARE_COST_HOURLY_RATE_CONTRACTED));" >&2
done