package ca.bc.gov.chefs.etl.constant;

import ca.bc.gov.chefs.etl.util.FileUtil;

import static ca.bc.gov.chefs.etl.constant.Constants.HEADERS;
import static ca.bc.gov.chefs.etl.constant.Constants.UNENC_FILE_PATH;
import static ca.bc.gov.chefs.etl.constant.Constants.ENC_FILE_PATH;

public class PCDConstants {
 	/* Decision Log Form */
	public final static String PCD_DECISION_LOG_PROPERTY = "pcd.decision.log.";
	public final static String PROPERTIES_PCD_DECISION_LOG = "pcd-decision-log-dir";
	public final static String PCD_DECISION_LOG_DIR = FileUtil.getDirectoryName(PROPERTIES_PCD_DECISION_LOG);
	public static final String PCD_DECISION_LOG_UNENCRYPTED_FP = FileUtil.buildDestinationPath(PROPERTIES_PCD_DECISION_LOG, false);
	public static final String PCD_DECISION_LOG_ENCRYPTED_FP = FileUtil.buildDestinationPath(PROPERTIES_PCD_DECISION_LOG, true);

	public final static String DECISION_LOG_SUBMISSIONS = "DECISION_LOG_SUBMISSIONS";
	public final static String DECISION_LOG_CHANGE_REQUEST_FILE_UPLOAD = "DECISION_LOG_CHANGE_REQUEST_FILE_UPLOAD";
	public final static String DECISION_LOG_PCN_NAMES = "DECISION_LOG_PCN_NAMES";
	public final static String DECISION_LOG_COMMENTS = "DECISION_LOG_COMMENTS";
	public final static String DECISION_LOG_INITIATIVES = "DECISION_LOG_INITIATIVES";

	static{
		UNENC_FILE_PATH.put(PCD_DECISION_LOG_DIR, PCD_DECISION_LOG_UNENCRYPTED_FP);
		ENC_FILE_PATH.put(PCD_DECISION_LOG_DIR, PCD_DECISION_LOG_ENCRYPTED_FP);

		HEADERS.put(DECISION_LOG_SUBMISSIONS, new String[] { 
			"SUBMISSION_ID", "CREATED_AT", "LATE_ENTRY", "SUBMITTER_FULL_NAME","SUBMITTER_USER_NAME",
			"SUBMITTER_EMAIL", "SUBMISSION_STATUS", "SUBMISSION_VERSION",
			"SUBMISSION_FORM_NAME", "HEALTH_AUTHORITY", "COMMUNITY_NAME", "TYPE_OF_INITIATIVE",
			"REQUEST_NUMBER", "SUBMITTED_DATE", "DESCRIPTION", "REQUEST_CATEGORY",
			"REQUEST_STATUS", "RECOMMENDED_DOCUMENTATION_TYPE", "OTHER_DOCUMENTS",
			"DATE_DECISION_MADE", "COMMENTS_RECOMMENDATIONS", "FINAL_DECISION_COMMENTS",
			"DECISION_MADE_BY", "FINAL_DECISION", "FINAL_DOCUMENTS_RECEIVED", "PRECEDENT_SETTING",
			"UPDATED_APPROVAL_TRACKER", "UPDATED_FINANCIAL_REPORT", "NOT_ALL_PCNS"
			});

		HEADERS.put(DECISION_LOG_CHANGE_REQUEST_FILE_UPLOAD, new String[] { 
			"ID", "URL", "SIZE","STORAGE", "ORIGINAL_NAME", "SUBMISSION_ID"
			});
		HEADERS.put(DECISION_LOG_PCN_NAMES, new String[] { 
			"SUBMISSION_ID", "PCN_NAME", "TYPE"
			});
		HEADERS.put(DECISION_LOG_COMMENTS, new String[] { 
			"SUBMISSION_ID", "COMMENT", "COMMENT_DATE"
			});
		HEADERS.put(DECISION_LOG_INITIATIVES, new String[] { 
			"SUBMISSION_ID", "INITIATIVE_NAME", "INITIATIVE_TYPE"
			});	
	}
}
