---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app.kubernetes.io/component: medis-etl-app
  app.kubernetes.io/instance: medis-etl-app
  app.kubernetes.io/name: medis-etl-app
  app.kubernetes.io/part-of: medis-etl
  app.openshift.io/runtime: java-springboot-camel
  app: "medis-etl-app"
  template: "medis-etl-app-bc-template"
metadata:
  name: "${REPO_NAME}-app-bc"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: medis-etl-image
    spec:
      lookupPolicy:
        local: false

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: medis-etl-app
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: medis-etl-image:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          uri: ${SOURCE_REPO_URL}
          ref: "main"
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: docker/Dockerfile
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
      - generic:
          secretReference:
            name: medis-etl-webhook-secret
        type: Generic
      - github:
          secretReference:
            name: medis-etl-github-webhook-secret
        type: GitHub
      - type: ConfigChange
parameters:
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    displayName: Source Repository URL
    required: true
