---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Webhook secrets
    openshift.io/display-name: MEDIS Webhook secrets
    openshift.io/long-description: This template creates secrets to be used for triggerring new build via webhook.
    tags: medis-etl
  name: medis-etl-secret
labels:
  app.kubernetes.io/component: app
  app.kubernetes.io/name: medis
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "12"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "medis-etl-webhook-secret"
    data:
      WebHookSecretKey: "${TOKEN}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "medis-etl-github-webhook-secret"
    data:
      WebHookSecretKey: "${TOKEN}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: medis-etl-secrets
    data:
      application.properties: |
        # properties used in route
        hostname = localhost
        port = 8080

        chefs.http.uri=https://submit.digital.gov.bc.ca/app/api/v1/forms/%s/export?format=json&type=submissions&minDate=%s&maxDate=%s

        aims.username=2f173b2b-2f3a-407a-aecf-6b4bdc9431ae
        aims.password=tbd

        ltc.facility.username=e1f4761f-efdd-4529-805e-677d3ae21601
        ltc.facility.password=tbd

        ltc.staffing.username=16ce36ca-9b4b-4ec6-bb75-96c2e1f258bb
        ltc.staffing.password=tbd

        ltc.ytd.username=256760e7-6e8b-44c4-8b63-51fb72c8c2cf
        ltc.ytd.password=tbd
      log4j2.properties: |
        appender.out.type = Console
        appender.out.name = out
        appender.out.layout.type = PatternLayout
        appender.out.layout.pattern = [%30.30t] %-30.30c{1} %-5p %m%n
        rootLogger.level = INFO
        rootLogger.appenderRef.out.ref = out
parameters:
  - name: TOKEN
    description: The token used to in the URL of Webhook.
    displayName: Webhook token
    required: true
