---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app.kubernetes.io/component: medis-etl-app
  app.kubernetes.io/instance: medis-etl-app
  app.kubernetes.io/name: medis-etl-app
  app.kubernetes.io/part-of: medis-etl
  app.openshift.io/runtime: java-springboot-camel
  app: "${APP_NAME}-${JOB_NAME}"
  template: "${REPO_NAME}-app-cm-template"
metadata:
  name: "${REPO_NAME}-app-cm"
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: medis-etl-encryption
    immutable: false
    data:
      hi-pub-key: |
        ${PUBLIC_KEY}
parameters:
  - name: APP_NAME
    description: Application name
    displayName: Application name
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    displayName: Job Branch Name
    required: true
  - name: REPO_NAME
    description: Application repository name
    displayName: Repository Name
    required: true
  - name: PUBLIC_KEY
    description: Public key for encryption
    displayName: Public key
    required: true
